version: "3"
services:
  app:
    restart: always
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_IMAGE_NAME} # goes to your repository on Docker Hub
    build:
      dockerfile: Dockerfile
      context: .
    container_name: "app"
    volumes:
      - node_modules:/app/node_modules
      - logs:/app/logs
      - type: bind
        source: yarn-error.log
        target: /app/yarn-error.log
    ports:
      - "80:80"

volumes:
  node_modules:
